### ISSUE TITLE
Is it possible to add the original Itho remote?

### ISSUE THREAD

**Issue by MavicPilot** [abaretta/Itho-WIFI-remote-Homey#1]
Your code is working successfully with my Itho fan. I can control it through API calls with Homey. Fan status is updated. 

Question: Is it possible to add the original Itho remote to the 'Itho WIFI remote' server? So the fan status will change on the server if the original Itho remote is used.

**Comment by abaretta** [comment]
Yes, this works (for me anyway). I can’t remember doing anything specific to set it up. I guess you could try to use the remote with the Itho ‘server’ in learning mode.
